version: '3.8'  # Specify the Docker Compose version

services:
  mysql1:
    image: mysql:latest
    container_name: mysql1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=rootpassword || exit 1"]
      interval: 10s
      retries: 5

  spring-app:
    image: nizarmlaouihi/gestion-station-ski:tagname
    container_name: spring-app
    ports:
      - "8089:8089"
    depends_on:
      - mysql1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql1:3306/springdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    networks:
      - spring-network

volumes:
  mysql-data:

networks:
  spring-network:
    driver: bridge