services:
  java-app:
    build:
      context: .
    ports:
      - "8089:8089"  # Correspondance entre l'intérieur et l'extérieur
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql1:3306/springdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - mysql1
    restart: always
    networks:
      - mynetwork

  mysql1:
    image: mysql:latest  # Spécifier une version stable
    container_name: mysql1
    ports:
      - "3307:3306"  # Port externe 3307, interne 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springdb
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - mynetwork

volumes:
  mysql-data:  # Volume persistant pour MySQL

networks:
  mynetwork:  # Réseau commun entre les services
    driver: bridge