version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: houssemino
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-spring:
    depends_on:
      - mysqldb
    #build: ./gestion-station-ski
    image: hazemhendi/ski-spring:1.0.0
    restart: on-failure
    ports:
      - "8069:8069"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/houssemino?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"}'
    stdin_open: true
    tty: true

  app-angular:
    depends_on:
      - app-spring
    #build: ./gestion-station-ski-ui
    image: hazemhendi/ski-angular:1.0.0
    ports:
      - "4200:4200"
    restart: on-failure

volumes:
  db: